### ISSUE TITLE
Win 10 Edge support

### ISSUE THREAD

**Issue by Morabaraba** [exsilium/cloud9#22]
This is more a fyi because it does not affect me. But I wanted to test the ctrl+v with edge and c9v2 does not seem to load.

````
HTML1300: Navigation occurred.
localhost:3131
Current window: localhost
SCRIPT65535: Invalid calling object
apf_release.js (39885,5)
SCRIPT438: Object doesn't support property or method 'getXmlDom'
apf_release.js (57982,17)
SCRIPT438: Object doesn't support property or method 'getXmlDom'
apf_release.js (57982,17)
SCRIPT438: Object doesn't support property or method 'getStyle'
apf_release.js (1168,9)
```

Is the js console output. I have the same instance open on chrome that is tip top!

**Comment by exsilium** [comment]
Good man for reporting. I've been working on restoring the APF pipeline and this bug might just raise my motivation to do it faster! Unfortunately, Ajax.org and C9 removed all the APF related repos. So currently I'm relying on the last forks that were around to get it stable. Still, good to track this here, thanks!

**Comment by Morabaraba** [comment]
> APF related repos

Sorry I'm not sure what `APF` is?

But for interested sake had a look at my backups and see I should have `node_modules` for `0.7.0` :P if that can be useful.

**Comment by exsilium** [comment]
Thanks, I've already taken the forks on what was left in Github but I haven't tried out to replace the one bundled in cloud9 (as of yet). The APF repos were used to *build* the apf_release.js file that is present in the cloud9 repo under `plugins-client/lib.apf/www/apf-packaged` directory. In it's combined (or built) form it's quite unmaintainable piece of js without any documentation :)

APF is/was the Ajax.org's JavaScript framework for creating realtime collaborative applications. This was LGPL licensed framework that also Cloud9v2 was based on. When C9v3 changed their licensing model and business direction, the APF (and related tooling) was abandoned/deleted as well, with a tweet stating that they will continue to develop it in-house (or merge with the C9 codebase).

There's an [old slideshare](https://www.slideshare.net/javruben/building-realtime-collaborative-apps-with-ajaxorg-platform/2-100_pure_JavaScript_framework_for) I found that gives a quick overview if you are interested in knowing more.

**Comment by exsilium** [comment]
Currently getting on Edge:

```
SCRIPT65535: Invalid calling object - apf_release.js (39901,4)
SCRIPT438: Object doesn't support property or method 'getStyle' - apf_release.js (1184,8)
```

**Comment by exsilium** [comment]
It seems that it is quite easy to get Edge up and running technically. APF requires the following changes:

- Detect Edge browser and identify it as Chrome + webkit compatible
- Fix `SCRIPT65535: Invalid calling object` by not calling: https://github.com/exsilium/apf/blob/master/core/browsers/non_ie.js#L160

**Comment by exsilium** [comment]
It opens, in development branch, yay!
