### ISSUE TITLE
Using without Node

### ISSUE THREAD

**Issue by berserk82** [exsilium/cloud9#25]
Hello there.
I would like to use the Cloud9 editor, I don't mind modifying it or writing plugins.
Can I use it without Node? If so, how?

Thanks in advance for any help.

Bye, Ivano.

**Comment by exsilium** [comment]
Hi @berserk82 ! I hope you are having a fine day. :sunglasses: 

Just for me to better understand your question, can you be more specific about your wish to use Cloud9 *without* Node and describe more what is your end goal?

Cloud9 uses both server and client side functionality, the server side explicitly relies on Node and several packages that provide basic transport functions like the Socket.io->Engine.io->Smith.io stack between the server and the client (browser).

From that point of view I would say, that **not** using Node would require a big rewrite of the server side components.

Or is your questions directed towards bundling Cloud9 to an application that would make it transparent to the user not needing to install Node separately? For that there are options like [nwjs](https://nwjs.io) and [electron](https://electron.atom.io) which could be used to bundle node and the rest of Cloud9 code to create an application that makes it transparent to the user that the Node is used as the underlying technology.

Cheers! :beers:

**Comment by berserk82** [comment]
Nevermind, I've switched to ACE, which works just fine.

**Comment by exsilium** [comment]
:+1: Cloud9 also uses ACE for the editing canvas part. Have fun!
