### ISSUE TITLE
Does running PM2 in C9 keep the workspace active?

### ISSUE THREAD

**Issue by Kovaelin** [exsilium/cloud9#45]
Does running PM2 in C9 keep the workspace active, or will it still hibernate after you leave?

**Comment by exsilium** [comment]
Just to be clear, this repository is about the self-host version of Cloud9v2. As such, the workplace will not be hibernated unless you setup such behavior in the first place. Apart from terminal sessions closing, the workspace will remain running.

**Comment by Kovaelin** [comment]
Thanks for the clarification.
