### ISSUE TITLE
setting breakpoint in editor window will confuse text input

### ISSUE THREAD

**Issue by mchen6** [exsilium/cloud9#51]
Dear cloud9 maintainers,

If I open a file from IDE and click to set a breakpoint on any line, the text input will be messed and no longer work, I have to close the file and reopen it to make it work again. This issue can be reproduced on  latest Chrome 69. Chrome console show below error messages. Is this a known issue of the IDE?

![1](https://user-images.githubusercontent.com/1168741/45274343-adbca080-b4e9-11e8-9e63-bed6f10719d2.png)

Below is a screenshot of the issue, thanks for your notice:

![1](https://user-images.githubusercontent.com/1168741/45274356-c1680700-b4e9-11e8-9ebe-30bfec210316.gif)

**Comment by exsilium** [comment]
Hi @mchen6 ! Thanks for the detailed report, will look into it! :wave:

**Comment by exsilium** [comment]
Issue should be fixed in `development` branch, let me know if it works for you to be included to the `v2.2.2` release. Cheers! :wave:

**Comment by mchen6** [comment]
Thanks for the great efforts! I did a test and this issue has disappeared in ```development``` branch.
