### ISSUE TITLE
cannot close opened image files

### ISSUE THREAD

**Issue by mchen6** [exsilium/cloud9#52]
Dear Cloud9 maintainers:

If I opened an image file in editor, I can't close it anymore. Chrome console show below error messages:

![image](https://user-images.githubusercontent.com/1168741/46002299-4f461380-c0e0-11e8-9922-25d68c3e1533.png)

This issue can be reproduced on ```master``` branch with latest Chrome 69, please refer to animated screenshot below, many thanks for your considerations:

![1](https://user-images.githubusercontent.com/1168741/46006065-3beb7600-c0e9-11e8-8beb-848e048ab64b.gif)

**Comment by exsilium** [comment]
Hi @mchen6 Sorry for your trouble.

This has been previously reported in  #46, fixed in `development` branch and will be included in the upcoming `v2.2.2` release (#50 )

Hope this helps! Cheers!

**Comment by mchen6** [comment]
Got it. Sorry that I should check previous issue logs before post this. Thanks for your comments
