### ISSUE TITLE
Where can i find terminal?

### ISSUE THREAD

**Issue by mvala** [exsilium/cloud9#6]
Hi,

I am new in cloud9 and i installed this version with terminal support. But i don't see tab "terminal". How can i activate it?

I see that terminal started
```
IDE server initialized. Listening on localhost:3131
[tty.js] Only accepting local connections.
[tty.js] Cloud9 terminal started, serving requests on port: 3131
[tty.js] 127.0.0.1 Session 127.0.0.1|Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36 created.
```
Thanks

**Comment by exsilium** [comment]
Closing this after 1.5 years :) If you have any issues using this fork or the terminal. Please let me know. Cheers!
