### ISSUE TITLE
which version node could work with 'terminal' branch?

### ISSUE THREAD

**Issue by wangyf2010** [exsilium/cloud9#7]
Some guys saying node-0.8.8 is perfect version for cloud9.
I tried it with ajaxorg/cloud9, it works great.

But after I merge 'terminal' code for ajaxorg/cloud9.
I got below error:
uv.h: file not found.

I'm not sure which version nodejs should be used by 'terminal' code?
Any suggestions?

**Comment by exsilium** [comment]
Modernized to work with 0.10+ node.js. Closing.
